# Generated by Django 3.0.5 on 2020-04-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodType', models.CharField(max_length=50)),
                ('timeToElapse', models.DecimalField(decimal_places=10, max_digits=20)),
                ('reportedCases', models.DecimalField(decimal_places=10, max_digits=20)),
                ('population', models.DecimalField(decimal_places=10, max_digits=20)),
                ('totalHospitalBeds', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infectionByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('severeCasesByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('hospitalBedsByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('casesForICUByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('casesForVentilatorsByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('dollarsInFlight', models.DecimalField(decimal_places=1, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='severeImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infectionByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('severeCasesByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('hospitalBedsByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('casesForICUByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('casesForVentilatorsByRequestedTime', models.DecimalField(decimal_places=1, max_digits=20)),
                ('dollarsInFlight', models.DecimalField(decimal_places=1, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avgAge', models.DecimalField(decimal_places=10, max_digits=20)),
                ('avgDailyIncomeInUSD', models.DecimalField(decimal_places=10, max_digits=20)),
                ('avgDailyIncomePopulation', models.DecimalField(decimal_places=10, max_digits=20)),
                ('regionDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='quickstart.data')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
